version: '3.1'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "db_vol:/var/lib/postgresql/data"

  lotus:
    image: nginx:alpine
    restart: always
    depends_on:
      - postgres
    ports: 
      - "8080:80"
    volumes:
      - "./frontend:/app/frontend"
      - "./nginx.conf:/etc/nginx/nginx.conf"

volumes:
  db_vol: