version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: asd123

  lotus:
    build: .
    restart: always
    depends_on:
      - mongo
    ports: 
      - "3000:3000"
